In [1]:
!pip install numpy

In [2]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
my_list2 = [1,3,5,3,9][ 10  40  90 
# print(my_list)
arr = np.array([my_list,my_list2])
print(arr)

[[1 2 3 4 5]
 [1 3 5 3 9]]


In [21]:
transpose = arr.reshape(5,2)
print(transpose)

[[1 2]
 [3 4]
 [5 1]
 [3 5]
 [3 9]]


In [43]:
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                
                [[7, 8, 9],
                 [10, 11, 12]]])

# print(arr)
# print("Dimensions:", arr.ndim)  # Output: 3
# print(arr.shape)
print(arr[0][0][0])
print(arr[-1,-1,-1])

1
12


In [28]:
array = np.ones((2, 3))  # 2 rows, 3 columns filled with zeros
print(array)
print(array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]]
2


In [30]:
import numpy as np

array = np.ones((1, 3, 4))  # 3D array: 2 blocks, 3 rows, 4 columns
print(array)
print("Shape:", array.shape)
print("Dimensions:", array.ndim)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Shape: (1, 3, 4)
Dimensions: 3


In [ ]:
print(array / 2)


[[[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]]


In [46]:

arr = np.array(["apple", "banana", "cherry"])
print(np.char.multiply(arr, 2))

['appleapple' 'bananabanana' 'cherrycherry']


In [71]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([[10, 20, 30],[1,2,4]])

In [72]:
print(arr1 + arr2)
# print(np.char.multiply(arr, arr1))

[[11 22 33]
 [ 2  4  7]]


In [65]:
import numpy as np

arr = np.arange(12).reshape(2, 2, 3)  # 3D: 2 blocks, 2 rows, 3 cols
print(arr)
print("Shape:", arr.shape)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Shape: (2, 2, 3)


In [10]:
# task 1 
marks = np.array([
    [78, 85, 90, 66],
    [88, 72, 95, 80],
    [60, 70, 65, 75],
    [92, 88, 84, 91],
    [55, 64, 58, 70]
])

print("Average per student:", marks.mean(axis=1))
print("Highest per subject:", marks.max(axis=0))
print("Index of student with lowest total:", marks.sum(axis=1).argmin())


Average per student: [79.75 83.75 67.5  88.75 61.75]
Highest per subject: [92 88 95 91]
Index of student with lowest total: 4


In [11]:
arr = np.arange(36)
arr_6x6 = arr.reshape(6, 6)
arr_3d = arr.reshape(3, 3, 4)

print("6x6 shape:", arr_6x6.shape)
print("3D shape:", arr_3d.shape)

6x6 shape: (6, 6)
3D shape: (3, 3, 4)


In [19]:
random_arr = np.random.randint(1, 101, size=(3, 4))
sorted_arr = np.sort(random_arr, axis=1)
row_sums = sorted_arr.sum(axis=1).reshape(-1, 1)
# print(row_sums)
new_arr = np.concatenate((sorted_arr, row_sums), axis=1)

print("Random array:\n", random_arr)
print("Sorted row-wise:\n", sorted_arr)
print("With row sums:\n", new_arr)

Random array:
 [[97  4 95 76]
 [95 71 11 97]
 [40 66 22 95]]
Sorted row-wise:
 [[ 4 76 95 97]
 [11 71 95 97]
 [22 40 66 95]]
With row sums:
 [[  4  76  95  97 272]
 [ 11  71  95  97 274]
 [ 22  40  66  95 223]]


In [25]:
arr = np.arange(1, 21)
new_arr = np.split(arr, 4)
print()
combined_arr = np.concatenate((new_arr[1], new_arr[3]))

print("Split parts:", new_arr)
print("Combined 2nd and 4th:", combined_arr)


Split parts: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20])]
Combined 2nd and 4th: [ 6  7  8  9 10 16 17 18 19 20]


In [29]:

arr = np.array([12, -5, 0, 23, -15, 45, 30, -2])
cleaned = arr[arr >= 0]
cleaned = np.insert(cleaned, 2, 99)
final_cleaned = np.sort(cleaned)

print(final_cleaned)




[ 0 12 23 30 45 99]


In [32]:

stock_prices = np.random.randint(100, 201, size=(2, 5, 3))
max_close = stock_prices[:, :, 2].max(axis=1)
lowest_open_day = stock_prices[:, :, 0].argmin(axis=1)

print("Stock prices:\n", stock_prices)
print("Max closing price per company:", max_close)
print("Lowest open day per company:", lowest_open_day)

Stock prices:
 [[[183 140 195]
  [127 134 184]
  [109 196 162]
  [128 121 108]
  [114 105 188]]

 [[170 200 130]
  [144 115 196]
  [112 179 100]
  [183 118 164]
  [138 124 189]]]
Max closing price per company: [195 196]
Lowest open day per company: [2 2]
